### ISSUE TITLE
R Bug

### ISSUE THREAD

**Issue by baileyji** [MazinLab/MKIDReadout#2]

**Comment by neelay893** [comment]
The problem was a flipped optimal filter - we thought the firmware was doing a correlation, but it was actually a convolution. 

Histogram of phase stream data optimally filtered by firmware:
![res70011_svffilt_fwoptfilt](https://user-images.githubusercontent.com/19984104/44376057-99b5ee00-a4ab-11e8-9af2-fc2f53c060f5.png)

Optimally filtered in software, using the same 50 tap filter loaded in firmware. R looks much better...
![res70011_svffilt_swoptfilt](https://user-images.githubusercontent.com/19984104/44376214-4e500f80-a4ac-11e8-8dd8-87c57c22ac19.png)

Optimally filtered by firmware, with a flipped filter coefficients loaded. R now agrees w/ software filtered data.
![res70011_svffilt_fwoptfiltflipped](https://user-images.githubusercontent.com/19984104/44376186-25c81580-a4ac-11e8-958f-e378396662c5.png)

Optimally filtered in software using a flipped template (convolution).
![res70011_svffilt_swoptfiltflipped](https://user-images.githubusercontent.com/19984104/44376097-bce09d80-a4ab-11e8-96da-9be60a5156ee.png)

**Comment by baileyji** [comment]
Reopening until fix committed.

**Comment by zobristnicholas** [comment]
Data from the 20180830 MEC run suggests that R~2 when it should be higher. The previous fix did not fully solve the problem

**Comment by neelay893** [comment]
Data taken on 9/13/2018 suggests that R from analog and digital readout are consistent w/ each other. R~2 on MEC seems to be a separate issue unrelated to the readout.
